import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

// POST /api/auth/register
// Creates auth user + company + user_profile + company_member (+ procurador_profile)
// Uses admin client (service role key) to bypass RLS
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      email, password, fullName, role = 'titular',
      cnpj, razaoSocial, nomeFantasia, tipo,
      // Procurador fields
      officeName, officeCnpj, officeCrc, officeOab, specialty,
      // Referral
      referralCode,
    } = body

    // Validate required fields
    if (!email || !password) {
      return NextResponse.json(
        { error: 'Email e senha sao obrigatorios.' },
        { status: 400 }
      )
    }

    if (role !== 'procurador' && (!cnpj || !razaoSocial)) {
      return NextResponse.json(
        { error: 'CNPJ e Razao Social sao obrigatorios.' },
        { status: 400 }
      )
    }

    if (role === 'procurador' && !officeName) {
      return NextResponse.json(
        { error: 'Nome do escritorio e obrigatorio.' },
        { status: 400 }
      )
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

    if (!supabaseUrl || !serviceRoleKey) {
      console.error('Missing env vars:', { hasUrl: !!supabaseUrl, hasKey: !!serviceRoleKey })
      return NextResponse.json(
        { error: 'Configuração do servidor incompleta. Contate o administrador.' },
        { status: 500 }
      )
    }

    const supabase = createClient(supabaseUrl, serviceRoleKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    })

    // ─── 1. Create auth user ───
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
    })

    if (authError) {
      if (authError.message?.includes('already been registered') || authError.message?.includes('already exists')) {
        return NextResponse.json(
          { error: 'Este email já está cadastrado. Tente fazer login.' },
          { status: 409 }
        )
      }
      console.error('Auth error:', authError)
      return NextResponse.json(
        { error: 'Erro ao criar usuario: ' + authError.message },
        { status: 400 }
      )
    }

    if (!authData.user) {
      return NextResponse.json({ error: 'Erro inesperado ao criar usuario' }, { status: 500 })
    }

    const userId = authData.user.id

    // Helper to rollback on failure
    async function rollback() {
      await supabase.auth.admin.deleteUser(userId)
    }

    // ─── 2. Create company record ───
    // For procurador: company is optional (only if officeCnpj provided)
    // For titular/representante: company is required
    let companyId: string | null = null

    if (role !== 'procurador') {
      const { data: company, error: compError } = await supabase
        .from('companies')
        .insert({
          auth_user_id: userId,
          cnpj: cnpj.replace(/\D/g, ''),
          razao_social: razaoSocial,
          nome_fantasia: nomeFantasia || razaoSocial.split(' ')[0],
          email,
          type: tipo || 'buyer',
          sefaz_status: 'pending',
          lgpd_consent: true,
          lgpd_consent_at: new Date().toISOString(),
        })
        .select('id')
        .single()

      if (compError) {
        await rollback()
        console.error('Company insert error:', compError)
        if (compError.message?.includes('duplicate') || compError.message?.includes('unique')) {
          return NextResponse.json({ error: 'Este CNPJ já está cadastrado.' }, { status: 409 })
        }
        return NextResponse.json(
          { error: 'Erro ao criar empresa: ' + compError.message },
          { status: 400 }
        )
      }
      companyId = company?.id || null
    }

    // ─── 3. Create user_profile ───
    const { data: profile, error: profileError } = await supabase
      .from('user_profiles')
      .insert({
        auth_user_id: userId,
        full_name: fullName || email.split('@')[0],
        email,
        role,
        // referral_code auto-generated by DB trigger for procuradores
      })
      .select('id, referral_code')
      .single()

    if (profileError) {
      // Rollback company + auth
      if (companyId) {
        await supabase.from('companies').delete().eq('id', companyId)
      }
      await rollback()
      console.error('Profile insert error:', profileError)
      return NextResponse.json(
        { error: 'Erro ao criar perfil: ' + profileError.message },
        { status: 400 }
      )
    }

    // ─── 4. Create company_member (link user → company) ───
    if (companyId && profile) {
      const permissions = role === 'titular'
        ? {
            can_list_credits: true,
            can_request_credits: true,
            can_approve_matches: true,
            can_sign_contracts: true,
            can_view_financials: true,
            can_manage_team: true,
          }
        : role === 'representante'
        ? {
            can_list_credits: true,
            can_request_credits: true,
            can_approve_matches: false,
            can_sign_contracts: false,
            can_view_financials: true,
            can_manage_team: false,
          }
        : {
            can_list_credits: true,
            can_request_credits: true,
            can_approve_matches: true,
            can_sign_contracts: false,
            can_view_financials: true,
            can_manage_team: false,
          }

      const { error: memberError } = await supabase
        .from('company_members')
        .insert({
          company_id: companyId,
          user_profile_id: profile.id,
          role,
          accepted_at: new Date().toISOString(),
          ...permissions,
        })

      if (memberError) {
        console.error('Member insert error (non-fatal):', memberError)
        // Non-fatal — user can still operate
      }
    }

    // ─── 5. Create procurador_profile (if procurador) ───
    let procuradorId: string | null = null

    if (role === 'procurador' && profile) {
      const { data: procData, error: procError } = await supabase
        .from('procurador_profiles')
        .insert({
          user_profile_id: profile.id,
          office_name: officeName,
          office_cnpj: officeCnpj ? officeCnpj.replace(/\D/g, '') : null,
          office_crc: officeCrc || null,
          office_oab: officeOab || null,
          specialty: specialty || null,
          status: 'active', // Auto-approve for now
          tier: 'bronze',
          approved_at: new Date().toISOString(),
        })
        .select('id')
        .single()

      if (procError) {
        console.error('Procurador insert error:', procError)
        // Non-fatal — profile exists, can complete later
      } else {
        procuradorId = procData?.id || null
      }
    }

    // ─── 6. Process referral code (if provided) ───
    if (referralCode && role !== 'procurador') {
      // Find the procurador who owns this referral code
      const { data: referrerProfile } = await supabase
        .from('user_profiles')
        .select('id')
        .eq('referral_code', referralCode.toUpperCase())
        .single()

      if (referrerProfile) {
        const { data: referrerProc } = await supabase
          .from('procurador_profiles')
          .select('id')
          .eq('user_profile_id', referrerProfile.id)
          .eq('status', 'active')
          .single()

        if (referrerProc && companyId) {
          // Create referral record
          await supabase.from('referral_invites').insert({
            procurador_id: referrerProc.id,
            invited_email: email,
            invited_cnpj: cnpj ? cnpj.replace(/\D/g, '') : null,
            invited_company_name: razaoSocial,
            referral_code: referralCode.toUpperCase(),
            status: 'accepted',
            accepted_at: new Date().toISOString(),
            accepted_by: profile?.id,
            company_id: companyId,
          })

          // Link procurador as company member
          await supabase.from('company_members').insert({
            company_id: companyId,
            user_profile_id: referrerProfile.id,
            role: 'procurador',
            can_list_credits: true,
            can_request_credits: true,
            can_approve_matches: true,
            can_sign_contracts: false,
            can_view_financials: true,
            can_manage_team: false,
            accepted_at: new Date().toISOString(),
            invited_by: profile?.id,
          })
        }
      }
    }

    return NextResponse.json({
      success: true,
      user_id: userId,
      company_id: companyId,
      profile_id: profile?.id,
      procurador_id: procuradorId,
      referral_code: profile?.referral_code,
      role,
      message: role === 'procurador'
        ? 'Escritorio cadastrado com sucesso! Bem-vindo ao programa de assessores.'
        : 'Conta criada com sucesso!',
    })
  } catch (error) {
    console.error('Register error:', error)
    return NextResponse.json(
      { error: 'Erro interno do servidor' },
      { status: 500 }
    )
  }
}
